# Generated by Django 4.2.6 on 2023-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fumother', models.CharField(max_length=150)),
                ('fufather', models.CharField(max_length=150)),
                ('chilfuname', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('national', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField(max_length=100)),
                ('xeroxbir', models.FileField(upload_to='bapfiles/')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
