# Generated by Django 4.2.6 on 2023-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0002_rename_contact_baptism_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('desired_date_of_blessing', models.CharField(max_length=150)),
                ('what_to_bless', models.CharField(max_length=150)),
                ('contact_number', models.IntegerField(max_length=100)),
                ('xerox_copy_valid_ID', models.FileField(upload_to='blessingfiles/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_number', models.IntegerField(max_length=100)),
                ('concern_type', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funerals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_mother_name', models.CharField(max_length=150)),
                ('full_father_name', models.CharField(max_length=150)),
                ('full_deceased_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('nationality_of_deceased', models.CharField(max_length=150)),
                ('date_of_birth_deceased', models.CharField(max_length=150)),
                ('date_of_death_deceased', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField(max_length=100)),
                ('xerox_copy_death_certificate', models.FileField(upload_to='funeralfiles/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_groom_name', models.CharField(max_length=150)),
                ('full_groom_father_name', models.CharField(max_length=150)),
                ('full_groom_mother_name', models.CharField(max_length=150)),
                ('groom_birthday', models.CharField(max_length=150)),
                ('full_bride_name', models.CharField(max_length=150)),
                ('full_bride_father_name', models.CharField(max_length=150)),
                ('full_bride_mother_name', models.CharField(max_length=150)),
                ('bride_birthday', models.CharField(max_length=150)),
                ('desired_marriage_date', models.CharField(max_length=150)),
                ('groom_nationality', models.CharField(max_length=150)),
                ('bride_nationality', models.CharField(max_length=150)),
                ('contact_number', models.IntegerField(max_length=100)),
                ('xerox_copy_license_marriage', models.FileField(upload_to='marriagefiles/')),
                ('xerox_copy_baptismal_confirmation', models.FileField(upload_to='marriagefiles/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='baptism',
            old_name='datecreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='baptism',
            old_name='nationality',
            new_name='nationality_of_child',
        ),
        migrations.RenameField(
            model_name='baptism',
            old_name='xerox_copy_birthcertificate',
            new_name='xerox_copy_birth_certificate',
        ),
    ]
