# Generated by Django 4.2.6 on 2023-12-06 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0003_blessing_contact_funerals_marriage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baptism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifichapel.baptism')),
                ('blessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifichapel.blessing')),
                ('funeral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifichapel.funerals')),
                ('marriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifichapel.marriage')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], max_length=15)),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifichapel.schedgroup')),
            ],
        ),
    ]
