# Generated by Django 4.2.6 on 2023-12-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0004_schedgroup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedgroup',
            name='baptism',
        ),
        migrations.RemoveField(
            model_name='schedgroup',
            name='blessing',
        ),
        migrations.RemoveField(
            model_name='schedgroup',
            name='funeral',
        ),
        migrations.RemoveField(
            model_name='schedgroup',
            name='marriage',
        ),
        migrations.AddField(
            model_name='schedgroup',
            name='baptism',
            field=models.ManyToManyField(related_name='client', to='ifichapel.baptism'),
        ),
        migrations.AddField(
            model_name='schedgroup',
            name='blessing',
            field=models.ManyToManyField(related_name='client', to='ifichapel.blessing'),
        ),
        migrations.AddField(
            model_name='schedgroup',
            name='funeral',
            field=models.ManyToManyField(related_name='client', to='ifichapel.funerals'),
        ),
        migrations.AddField(
            model_name='schedgroup',
            name='marriage',
            field=models.ManyToManyField(related_name='client', to='ifichapel.marriage'),
        ),
    ]
