# Generated by Django 4.2.6 on 2023-12-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0005_remove_schedgroup_baptism_remove_schedgroup_blessing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], max_length=15)),
                ('baptism', models.ManyToManyField(related_name='client', to='ifichapel.baptism')),
                ('blessing', models.ManyToManyField(related_name='client', to='ifichapel.blessing')),
                ('funeral', models.ManyToManyField(related_name='client', to='ifichapel.funerals')),
                ('marriage', models.ManyToManyField(related_name='client', to='ifichapel.marriage')),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='SchedGroup',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
