# Generated by Django 4.2.6 on 2023-12-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0006_schedstatus_remove_status_schedule_delete_schedgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funerals',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedstatus',
            name='baptism',
            field=models.ManyToManyField(blank=True, related_name='client', to='ifichapel.baptism'),
        ),
        migrations.AlterField(
            model_name='schedstatus',
            name='blessing',
            field=models.ManyToManyField(blank=True, related_name='client', to='ifichapel.blessing'),
        ),
        migrations.AlterField(
            model_name='schedstatus',
            name='funeral',
            field=models.ManyToManyField(blank=True, related_name='client', to='ifichapel.funerals'),
        ),
        migrations.AlterField(
            model_name='schedstatus',
            name='marriage',
            field=models.ManyToManyField(blank=True, related_name='client', to='ifichapel.marriage'),
        ),
    ]
