# Generated by Django 4.2.6 on 2023-12-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0007_alter_baptism_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=150),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='desired_date_of_blessing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='what_to_bless',
            field=models.CharField(choices=[('H', 'House'), ('V', 'Vehicle'), ('I', 'Item')], max_length=150),
        ),
        migrations.AlterField(
            model_name='funerals',
            name='date_of_birth_deceased',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funerals',
            name='date_of_death_deceased',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funerals',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='bride_birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='desired_marriage_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='groom_birthday',
            field=models.DateField(),
        ),
    ]
