# Generated by Django 4.2.6 on 2023-12-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0009_remove_schedstatus_baptism_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedstatus',
            name='baptism',
        ),
        migrations.RemoveField(
            model_name='schedstatus',
            name='blessing',
        ),
        migrations.RemoveField(
            model_name='schedstatus',
            name='funeral',
        ),
        migrations.RemoveField(
            model_name='schedstatus',
            name='marriage',
        ),
        migrations.AddField(
            model_name='schedstatus',
            name='baptism',
            field=models.ManyToManyField(blank=True, related_name='client', to='ifichapel.baptism'),
        ),
        migrations.AddField(
            model_name='schedstatus',
            name='blessing',
            field=models.ManyToManyField(blank=True, related_name='client', to='ifichapel.blessing'),
        ),
        migrations.AddField(
            model_name='schedstatus',
            name='funeral',
            field=models.ManyToManyField(blank=True, related_name='client', to='ifichapel.funerals'),
        ),
        migrations.AddField(
            model_name='schedstatus',
            name='marriage',
            field=models.ManyToManyField(blank=True, related_name='client', to='ifichapel.marriage'),
        ),
    ]
