# Generated by Django 4.2.6 on 2023-12-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0010_remove_schedstatus_baptism_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedstatus',
            name='Status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], max_length=100),
        ),
    ]
