# Generated by Django 4.2.6 on 2024-01-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0011_alter_schedstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='paying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_date_of_schedule', models.DateField()),
                ('upload_receipt', models.FileField(upload_to='paymentreceipts/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='desired_marriage_date',
        ),
    ]
