# Generated by Django 4.2.6 on 2024-01-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0013_alter_paying_desired_date_of_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blessing',
            name='desired_date_of_blessing',
        ),
        migrations.AlterField(
            model_name='funerals',
            name='date_of_birth_deceased',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='funerals',
            name='date_of_death_deceased',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='bride_birthday',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='groom_birthday',
            field=models.CharField(max_length=150),
        ),
    ]
