# Generated by Django 4.2.6 on 2024-01-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0014_remove_blessing_desired_date_of_blessing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paying',
            name='full_name_of_scheduled_person',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
