# Generated by Django 4.2.6 on 2024-01-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0015_paying_full_name_of_scheduled_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paying',
            name='full_name_of_scheduled_person',
        ),
        migrations.AddField(
            model_name='paying',
            name='baptism',
            field=models.ManyToManyField(blank=True, related_name='person', to='ifichapel.baptism'),
        ),
        migrations.AddField(
            model_name='paying',
            name='blessing',
            field=models.ManyToManyField(blank=True, related_name='person', to='ifichapel.blessing'),
        ),
        migrations.AddField(
            model_name='paying',
            name='funeral',
            field=models.ManyToManyField(blank=True, related_name='person', to='ifichapel.funerals'),
        ),
        migrations.AddField(
            model_name='paying',
            name='marriage',
            field=models.ManyToManyField(blank=True, related_name='person', to='ifichapel.marriage'),
        ),
    ]
