# Generated by Django 4.2.6 on 2024-01-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifichapel', '0016_remove_paying_full_name_of_scheduled_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paying',
            old_name='baptism',
            new_name='baptismz',
        ),
        migrations.RenameField(
            model_name='paying',
            old_name='blessing',
            new_name='blessingz',
        ),
        migrations.RenameField(
            model_name='paying',
            old_name='funeral',
            new_name='funeralz',
        ),
        migrations.RenameField(
            model_name='paying',
            old_name='marriage',
            new_name='marriagez',
        ),
    ]
